### ISSUE TITLE
Timestamp of usernote is always the date/time when the program was started

### ISSUE THREAD

**Issue by Santi871** [teaearlgraycold/puni#6]
https://github.com/teaearlgraycold/puni/blob/master/puni/base.py#L44

In `note_time=int(time.time())` the method only runs once when the module gets imported because it's a method in a default parameter, so all usernotes have the program startup's timestamp if `note_time` is not passed.

**Comment by danthedaniel** [comment]
Thanks for catching that! It's been resolved in 1.1.2:

https://github.com/teaearlgraycold/puni/commit/f6d0bfde99942b29a6f91273e48abcd2d7a94c93
